[build]
    publish = "./docs/dist"
    command = "pnpm run build || ( npm install pnpm turbo && pnpm i && pnpm run build )"
[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"
    