[build]
    publish = "./build"
    command = "( pnpm install --no-frozen-lockfile  || npm install pnpm turbo ) && cd .. && pnpm install --no-frozen-lockfile  && npx turbo run build --scope=docs --include-dependencies --no-deps"
[build.environment]
    NODE_VERSION = "14"
    NPM_FLAGS = "--prefix=/dev/null"
    